#!/usr/bin/env bash
#
# onboard-client.sh — provision one client workspace on the editor VPS.
#
#   sudo ./onboard-client.sh <slug> <git-repo-url> [base-domain]
#
# Idempotent and non-destructive: re-running NEVER discards an existing
# checkout (a client may have unpushed edits) and reuses the already
# allocated port. It only fills in whatever is missing, then reloads.
#
# What it does:
#   1. /srv/clients/<slug>/{site,.state}  (git clone first run only)
#   2. /etc/flowstarter/clients/<slug>.env  (port reused if present)
#   3. nginx vhost from nginx-site.conf.tmpl  ->  test  ->  reload
#   4. systemctl enable --now flowstarter-editor@<slug>
#   5. prints the Cloudflare DNS record to add (does NOT touch DNS)
#
# Prereqs (one-time, see docs/EDITOR_DEPLOYMENT.md): flowstarter user,
# /opt/flowstarter/bin/run-editor.sh, /etc/flowstarter/editor.env,
# flowstarter-editor@.service, nginx-shared.conf, the origin cert.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

err() { printf 'error: %s\n' "$*" >&2; exit 1; }
info() { printf '\033[1m==>\033[0m %s\n' "$*"; }

[[ ${EUID} -eq 0 ]] || err "run as root (sudo)"
[[ $# -ge 2 ]] || err "usage: $0 <slug> <git-repo-url> [base-domain]"

SLUG="$1"
REPO_URL="$2"
BASE_DOMAIN="${3:-${FLOWSTARTER_BASE_DOMAIN:-}}"
PORT_RANGE_START="${FLOWSTARTER_PORT_RANGE_START:-5800}"
PORT_RANGE_END="${FLOWSTARTER_PORT_RANGE_END:-5999}"

[[ -n "${BASE_DOMAIN}" ]] || err "base-domain required (arg 3 or \$FLOWSTARTER_BASE_DOMAIN)"
[[ "${SLUG}" =~ ^[a-z0-9][a-z0-9-]{1,40}$ ]] \
  || err "slug must match ^[a-z0-9][a-z0-9-]{1,40}$ (got '${SLUG}')"

CLIENT_ROOT="/srv/clients/${SLUG}"
SITE_DIR="${CLIENT_ROOT}/site"
STATE_DIR="${CLIENT_ROOT}/.state"
ENV_DIR="/etc/flowstarter/clients"
ENV_FILE="${ENV_DIR}/${SLUG}.env"
NGINX_AVAIL="/etc/nginx/sites-available/flowstarter-editor-${SLUG}.conf"
NGINX_ENABLED="/etc/nginx/sites-enabled/flowstarter-editor-${SLUG}.conf"
TMPL="${SCRIPT_DIR}/nginx-site.conf.tmpl"

[[ -f "${TMPL}" ]] || err "template not found: ${TMPL}"
id flowstarter &>/dev/null || err "system user 'flowstarter' missing (run base provisioning first)"

# --- 1. Directories + first-run checkout ----------------------------
install -d -o flowstarter -g flowstarter -m 0755 "${CLIENT_ROOT}"
install -d -o flowstarter -g flowstarter -m 0700 "${STATE_DIR}"

if [[ -e "${SITE_DIR}/.git" ]]; then
  info "site checkout exists — leaving it untouched (won't discard local edits)"
elif [[ -e "${SITE_DIR}" ]]; then
  err "${SITE_DIR} exists but is not a git repo — refusing to overwrite; inspect manually"
else
  info "cloning ${REPO_URL} -> ${SITE_DIR}"
  sudo -u flowstarter git clone "${REPO_URL}" "${SITE_DIR}"
fi

# --- 2. Per-workspace env (reuse port if already assigned) ----------
install -d -o root -g flowstarter -m 0750 "${ENV_DIR}"

PORT=""
if [[ -f "${ENV_FILE}" ]]; then
  PORT="$(awk -F= '/^T3CODE_PORT=/{print $2}' "${ENV_FILE}" | tr -d '[:space:]')"
  [[ -n "${PORT}" ]] && info "reusing existing port ${PORT} for ${SLUG}"
fi

if [[ -z "${PORT}" ]]; then
  declare -A USED=()
  shopt -s nullglob
  for f in "${ENV_DIR}"/*.env; do
    p="$(awk -F= '/^T3CODE_PORT=/{print $2}' "${f}" | tr -d '[:space:]')"
    [[ -n "${p}" ]] && USED["${p}"]=1
  done
  shopt -u nullglob
  for ((cand = PORT_RANGE_START; cand <= PORT_RANGE_END; cand++)); do
    if [[ -z "${USED[${cand}]:-}" ]]; then PORT="${cand}"; break; fi
  done
  [[ -n "${PORT}" ]] || err "no free port in ${PORT_RANGE_START}-${PORT_RANGE_END}"
  info "allocated port ${PORT} for ${SLUG}"
fi

# Written atomically; secrets stay in the shared editor.env, not here.
TMP_ENV="$(mktemp)"
cat > "${TMP_ENV}" <<EOF
# Generated by onboard-client.sh for workspace '${SLUG}'. Safe to edit
# the port only if you also reload nginx + restart the unit.
T3CODE_PORT=${PORT}
T3CODE_HOME=${STATE_DIR}
T3CODE_PROJECT_DIR=${SITE_DIR}
T3CODE_AUTO_BOOTSTRAP_PROJECT_FROM_CWD=true
FLOWSTARTER_WORKSPACE_SLUG=${SLUG}
EOF
install -o root -g flowstarter -m 0640 "${TMP_ENV}" "${ENV_FILE}"
rm -f "${TMP_ENV}"

# --- 3. nginx vhost -------------------------------------------------
TMP_NGINX="$(mktemp)"
sed -e "s/__SLUG__/${SLUG}/g" \
    -e "s/__PORT__/${PORT}/g" \
    -e "s/__BASE_DOMAIN__/${BASE_DOMAIN}/g" \
    "${TMPL}" > "${TMP_NGINX}"
install -o root -g root -m 0644 "${TMP_NGINX}" "${NGINX_AVAIL}"
rm -f "${TMP_NGINX}"
ln -sfn "${NGINX_AVAIL}" "${NGINX_ENABLED}"

info "nginx -t"
nginx -t
systemctl reload nginx

# --- 4. systemd instance -------------------------------------------
info "starting flowstarter-editor@${SLUG}"
systemctl enable --now "flowstarter-editor@${SLUG}.service"
systemctl --no-pager --lines=0 status "flowstarter-editor@${SLUG}.service" || true

# --- 5. DNS (print only — never mutate an external account here) ----
SERVER_IP="$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo '<server-ip>')"
cat <<EOF

$(info "DONE — workspace '${SLUG}' is live once DNS resolves")

Add this Cloudflare DNS record (proxied / orange-cloud):

    Type: A
    Name: ${SLUG}.app
    Value: ${SERVER_IP}
    Proxy: ON

Then set a Cloudflare cache rule for '${SLUG}.app.${BASE_DOMAIN}' = Bypass
(the editor must never be cached). Editor URL:

    https://${SLUG}.app.${BASE_DOMAIN}

EOF
