/**
 * One-shot provisioner: a Hetzner cpx22 host in fsn1, bootstrapped via
 * the canonical lib/hosting/cloud-init.ts (Caddy + Docker + Node22 +
 * claude CLI + ufw + deploy-agent placeholder). Labelled
 * `workspace=lebadusul` and `purpose=editor`. The Editor Docker image
 * is built on the box in the next stage, not here.
 *
 * Idempotent: refuses to spawn a second host if one with
 * label `workspace=lebadusul` already exists.
 *
 * Run:
 *   pnpm --filter flowstarter exec tsx scripts/provision-lebadusul.ts
 */

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import path from "node:path";

import { hetznerFromEnv } from "../src/lib/hosting/hetzner";
import { buildCloudInit, getCloudInitVersion } from "../src/lib/hosting/cloud-init";

// --- env (no dotenv dep needed) -------------------------------------
function loadEnvFile(p: string) {
  if (!existsSync(p)) return;
  for (const line of readFileSync(p, "utf-8").split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (!m) continue;
    if (!process.env[m[1]!]) process.env[m[1]!] = m[2]!.replace(/^"|"$/g, "");
  }
}
const HERE = path.dirname(new URL(import.meta.url).pathname);
const ENVF = path.resolve(HERE, "..", ".env.local");
loadEnvFile(ENVF);
loadEnvFile(path.resolve(HERE, "..", ".env"));

if (!process.env.HETZNER_API_TOKEN) {
  console.error("missing HETZNER_API_TOKEN");
  process.exit(1);
}

const LABEL_WS = "lebadusul";
const SSH_KEY_NAME = "flowstarter";
const HOSTNAME = "lebadusul-editor-01";
const CADDY_EMAIL = "ops@flowstarter.net";

// --- main -----------------------------------------------------------
async function main() {
  const client = hetznerFromEnv();

  // 1. Refuse to duplicate.
  const existing = await client.listServers();
  const dup = existing.servers.find((s) => s.labels?.workspace === LABEL_WS);
  if (dup) {
    console.log(
      `Server already exists for workspace=${LABEL_WS}: id=${dup.id} name=${dup.name} ` +
        `ipv4=${dup.public_net?.ipv4?.ip ?? "-"} status=${dup.status}. Aborting.`,
    );
    return;
  }

  // 2. Resolve SSH key id by name (so the script isn't tied to a numeric id).
  const sshList = (await fetch("https://api.hetzner.cloud/v1/ssh_keys", {
    headers: { Authorization: `Bearer ${process.env.HETZNER_API_TOKEN!}` },
  }).then((r) => r.json())) as { ssh_keys: Array<{ id: number; name: string }> };
  const sshKey = sshList.ssh_keys.find((k) => k.name === SSH_KEY_NAME);
  if (!sshKey) {
    console.error(`SSH key "${SSH_KEY_NAME}" not found in this project's keys`);
    process.exit(1);
  }

  // 3. Generate (or reuse) the deploy-agent shared secret, persist to .env.local.
  let deployAgentSharedSecret = process.env.DEPLOY_AGENT_SHARED_SECRET;
  if (!deployAgentSharedSecret) {
    deployAgentSharedSecret = randomBytes(32).toString("hex");
    appendFileSync(
      ENVF,
      `\n# Generated by provision-lebadusul.ts on ${new Date().toISOString()}\n` +
        `DEPLOY_AGENT_SHARED_SECRET=${deployAgentSharedSecret}\n`,
    );
    console.log("DEPLOY_AGENT_SHARED_SECRET generated → appended to .env.local");
  }

  // 4. Build cloud-init (deploy-agent install is null — we run the editor
  //    directly via docker for v1; deploy-agent can be added later).
  const userData = buildCloudInit({
    hostname: HOSTNAME,
    caddyAcmeEmail: CADDY_EMAIL,
    deployAgentSharedSecret,
    deployAgentArtifactUrl: null,
    anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? null,
  });
  console.log(`cloud-init built (version ${getCloudInitVersion()}, ${userData.length} bytes)`);

  // 5. Create the server.
  console.log(`creating server "${HOSTNAME}" (cpx22 / fsn1 / ubuntu-24.04)…`);
  const resp = await client.createServer({
    name: HOSTNAME,
    server_type: "cpx22",
    location: "fsn1",
    image: "ubuntu-24.04",
    ssh_keys: [sshKey.id],
    user_data: userData,
    labels: { purpose: "editor", workspace: LABEL_WS },
    start_after_create: true,
  });

  const s = resp.server;
  console.log("");
  console.log("=== CREATED ===");
  console.log(`  id        ${s.id}`);
  console.log(`  name      ${s.name}`);
  console.log(`  status    ${s.status}`);
  console.log(`  ipv4      ${s.public_net?.ipv4?.ip ?? "-"}`);
  console.log(`  ipv6      ${s.public_net?.ipv6?.ip ?? "-"}`);
  console.log(`  location  ${s.datacenter?.location?.name ?? "-"}`);
  console.log(`  labels    ${JSON.stringify(s.labels ?? {})}`);
  console.log(`  cloud-init v${getCloudInitVersion()} — first boot bootstrap ~5-10 min`);
}

main().catch((err) => {
  console.error("FAILED:", err instanceof Error ? err.message : err);
  process.exit(1);
});
