/* eslint-disable */
/**
 * Generated by `npx convex codegen`.
 *
 * To regenerate, run `npx convex dev` or `npx convex codegen`.
 * @module
 */

import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = anyApi;
export const internal = anyApi;
