/* eslint-disable */
/**
 * Generated by `npx convex codegen`.
 *
 * To regenerate, run `npx convex dev` or `npx convex codegen`.
 * @module
 */

import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
} from "convex/server";

/**
 * Define a query in this Convex app's public API.
 */
export const query = queryGeneric;

/**
 * Define a query that is only callable by other Convex functions (but not from the client).
 */
export const internalQuery = queryGeneric;

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = mutationGeneric;

/**
 * Define a mutation that is only callable by other Convex functions (but not from the client).
 */
export const internalMutation = mutationGeneric;

/**
 * Define an action in this Convex app's public API.
 */
export const action = actionGeneric;

/**
 * Define an action that is only callable by other Convex functions (but not from the client).
 */
export const internalAction = actionGeneric;

/**
 * Define an HTTP action.
 */
export const httpAction = httpActionGeneric;
