/* eslint-disable */
/**
 * Generated by `npx convex codegen`.
 *
 * To regenerate, run `npx convex dev` or `npx convex codegen`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

import type * as assets from "../assets.js";
import type * as clients from "../clients.js";
import type * as conversations from "../conversations.js";
import type * as costs from "../costs.js";
import type * as editorSessions from "../editorSessions.js";
import type * as feedback from "../feedback.js";
import type * as files from "../files.js";
import type * as http from "../http.js";
import type * as lib_schemas from "../lib/schemas.js";
import type * as logos from "../logos.js";
import type * as magicLinks from "../magicLinks.js";
import type * as projects from "../projects.js";
import type * as snapshots from "../snapshots.js";
import type * as supabaseReviewArtifacts from "../supabaseReviewArtifacts.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  assets: typeof assets;
  clients: typeof clients;
  conversations: typeof conversations;
  costs: typeof costs;
  editorSessions: typeof editorSessions;
  feedback: typeof feedback;
  files: typeof files;
  http: typeof http;
  "lib/schemas": typeof lib_schemas;
  logos: typeof logos;
  magicLinks: typeof magicLinks;
  projects: typeof projects;
  snapshots: typeof snapshots;
  supabaseReviewArtifacts: typeof supabaseReviewArtifacts;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
