/**
 * Premium Site Generation System Prompt
 * 
 * Guidelines for generating outstanding, non-generic websites
 */

export const PREMIUM_SITE_SYSTEM_PROMPT = `
## CRITICAL: Avoid AI Slop

You are creating a PREMIUM website that must look like it was designed by a top agency, NOT generated by AI.

### AVOID These Generic Patterns (AI Slop):
- "Transform your [X]" headlines
- "Welcome to [Business Name]"  
- "We are passionate about..."
- "Our team of experts..."
- "Quality service you can trust"
- "Your satisfaction is our priority"
- Generic testimonials like "Great service! 5 stars!"
- Placeholder text that sounds like Lorem Ipsum
- Overused phrases: "cutting-edge", "innovative", "world-class", "seamless"
- Generic CTAs: "Learn More", "Get Started", "Contact Us"

### DO Create:
- **Headlines that are specific and bold**: Use numbers, specifics, or provocative statements
  - Bad: "Transform Your Fitness Journey"
  - Good: "15 Minutes. Zero Excuses. Real Results."
  
- **Copy that sounds human**: Write like a confident expert talking to a friend
  - Bad: "We provide comprehensive fitness solutions tailored to your needs"
  - Good: "Most people don't need more time in the gym. They need the right 15 minutes."

- **CTAs that create urgency or curiosity**:
  - Bad: "Get Started"
  - Good: "See the 15-Minute Method" or "Book Your Free Assessment"

- **Specific testimonials with personality**:
  - Bad: "Great trainer! Highly recommend!"
  - Good: "I was skeptical about 15-minute workouts until I dropped 20 lbs in 3 months. Now I'm that annoying person who won't shut up about it. - Sarah K., Marketing Director"

### Visual Design Principles:

1. **Color Application**:
   - Primary color: Used sparingly for CTAs and key accents (10-15%)
   - Secondary color: Supporting elements, hover states
   - Neutral base: 70%+ of the design should be neutral tones
   - Don't rainbow-wash everything with the brand color

2. **Typography Hierarchy**:
   - Headlines: Bold, impactful, can break rules
   - Subheadlines: Supportive, add context
   - Body: Easy to read, generous line height
   - Mix weights strategically (not everything bold)

3. **Whitespace**:
   - More whitespace = more premium feel
   - Let content breathe
   - Sections should have clear separation
   - Don't cram content together

4. **Visual Elements**:
   - Use gradients subtly (not garish)
   - Add depth with shadows (soft, realistic)
   - Include micro-interactions on hover
   - Background patterns/textures should be subtle

5. **Layout**:
   - Asymmetry creates interest
   - Break the grid occasionally
   - Overlap elements for depth
   - Use negative space intentionally

### Section Structure (Don't Just Stack Sections):

1. **Hero**: Make a bold statement, show don't tell
2. **Social Proof**: Logos, numbers, or quick wins (build trust fast)
3. **Problem/Solution**: Address the pain point directly
4. **Features/Services**: Focus on outcomes, not features
5. **Proof**: Detailed testimonials, case studies, results
6. **About**: Human story, not corporate speak
7. **CTA**: Clear, urgent, low-friction

### Content Rules:

- Every headline should be tweetable (punchy, memorable)
- Features → Benefits → Outcomes (don't stop at features)
- Use odd numbers in lists (3 or 5, not 4)
- Include specific numbers when possible (87% success rate > "high success rate")
- Break up text with visual elements
- End sections with micro-CTAs

### The "Would I Screenshot This?" Test:

Before finalizing any section, ask: "Would someone screenshot this and share it?"
If not, it's not good enough. Make it:
- Visually striking
- Quotable
- Unique to this brand

Remember: A premium website doesn't look "designed" - it looks inevitable, like this is the only way this brand could be presented.
`;

/**
 * Get industry-specific content guidance
 */
export function getIndustryGuidance(industry: string): string {
  const industryLower = industry.toLowerCase();
  
  if (industryLower.includes('fitness') || industryLower.includes('gym')) {
    return `
### Fitness Industry Specifics:
- Lead with RESULTS, not equipment or facilities
- Show transformation without being cliché (no "before/after" sliders)
- Emphasize time efficiency (busy professionals hate long workouts)
- Use action words: crush, build, push, achieve
- Testimonials should mention specific metrics (lbs lost, PRs hit)
- Avoid: generic gym stock photos, overly muscular models, "no pain no gain"
`;
  }
  
  if (industryLower.includes('restaurant') || industryLower.includes('food')) {
    return `
### Restaurant Industry Specifics:
- Food photography is everything - it must look appetizing
- Show the experience, not just the food (ambiance, people enjoying)
- Menu items need evocative descriptions (not just ingredients)
- Include chef's story or food philosophy
- Emphasize fresh, local, seasonal if applicable
- Avoid: generic "delicious food" copy, clipart-style graphics
`;
  }
  
  if (industryLower.includes('tech') || industryLower.includes('saas')) {
    return `
### Tech/SaaS Industry Specifics:
- Lead with the problem you solve, not features
- Show the product in context (not just screenshots)
- Use social proof from recognizable companies if possible
- Pricing should be clear and confident
- Include integration logos if relevant
- Avoid: buzzword soup, generic dashboard screenshots, "revolutionary" claims
`;
  }
  
  return `
### Professional Services:
- Lead with expertise and results
- Show the human behind the service
- Include specific case studies or outcomes
- Build trust through transparency
- Make the process clear and approachable
`;
}

/**
 * Generate palette application CSS
 */
export function generatePaletteCSS(palette: {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
}): string {
  return `
:root {
  /* Primary - Use sparingly for CTAs and key accents */
  --color-primary: ${palette.primary};
  --color-primary-hover: color-mix(in srgb, ${palette.primary} 85%, black);
  --color-primary-light: color-mix(in srgb, ${palette.primary} 15%, white);
  
  /* Secondary - Supporting elements */
  --color-secondary: ${palette.secondary};
  --color-secondary-hover: color-mix(in srgb, ${palette.secondary} 85%, black);
  
  /* Accent - Special highlights */
  --color-accent: ${palette.accent};
  
  /* Backgrounds - Most of the design */
  --color-bg: ${palette.background};
  --color-bg-elevated: color-mix(in srgb, ${palette.background} 95%, white);
  --color-bg-muted: color-mix(in srgb, ${palette.background} 90%, ${palette.primary});
  
  /* Text - High contrast for readability */
  --color-text: color-mix(in srgb, ${palette.background} 10%, white);
  --color-text-muted: color-mix(in srgb, ${palette.background} 40%, white);
  
  /* Borders and dividers */
  --color-border: color-mix(in srgb, ${palette.background} 80%, white);
}

/* Apply palette with restraint */
.btn-primary {
  background: var(--color-primary);
  color: white;
}

.btn-secondary {
  background: transparent;
  border: 2px solid var(--color-primary);
  color: var(--color-primary);
}

/* Gradients should be subtle */
.gradient-bg {
  background: linear-gradient(
    135deg, 
    var(--color-bg) 0%, 
    var(--color-bg-muted) 100%
  );
}

/* Accent color used minimally */
.highlight {
  color: var(--color-accent);
}

.badge {
  background: var(--color-primary-light);
  color: var(--color-primary);
}
`;
}

